apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: new-replica-set
  labels:
    app: replicaset
spec:
  template:
    metadata:
      name: myapp-pod-nginx
      labels:
        app: myapp-nginx
        type: front-end
    spec:
      containers:
        - name: nginx-container
          image: nginx
  replicas: 4
  selector:
    matchLabels:
      type: front-end
