apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  labels:
    app: web-service
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30080
  selector:
    app: my-nginx-server
